#define DEBUG_MODE			0


#define SHOW_SYMBOL_TABLE	(0*DEBUG_MODE)
#define SHOW_LABLE			(0*DEBUG_MODE)
#define SHOW_COMMAND		(1*DEBUG_MODE)
#define SHOW_OPERANDS		(1*DEBUG_MODE)
#define SHOW_IC				(0*DEBUG_MODE)
#define SHOW_DC				(0*DEBUG_MODE)
#define SHOW_FINAL_COUNTERS	(1*DEBUG_MODE)
#define SHOW_DATA_ARR_I		(0*DEBUG_MODE)

#define SHOW_TAKE			(3*DEBUG_MODE) /* can be 0,1,2, 3 */
#define SHOW_ENCODING		(0*DEBUG_MODE)
#define SHOW_GENERAL		(1*DEBUG_MODE)

#define FILE_BINARY_PRINT	(0*DEBUG_MODE)

#define VALIDATE_LABLE		(0*DEBUG_MODE)
#define VALIDATE_OPERANDS	(0*DEBUG_MODE)


